In [2]:
import pandas as pd

df = pd.read_csv("mtcar.csv") #.csv파일 불러오기
df.head() # 맨 앞부터 5줄 불러오기

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [3]:
df.tail() # 맨 뒤부터 5줄

model   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

In [7]:
df[25:29] # 특정 범위의 정보를 보고싶다면 슬라이싱

model   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
25       Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.9   1   1     4   
26   Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.7   0   1     5   
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   

    carb  
25     1  
26     2  
27     2  
28     4

In [8]:
df.columns

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [9]:
# 통계정보를 간략하게 알려주는 함수
df.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [10]:
# 평균 구하기
# 각각 column 들의 평균을 확인할 수 있다
df.mean()

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [4]:
# cyl 변수의 hp 평균값 구하기
# cyl = 실린더 수: 4개 6개 8개 기준 hp 평균을 보여주고 있음
df.groupby(['cyl']).mean()

mpg        disp          hp      drat        wt       qsec  \
cyl                                                                     
4    26.663636  105.136364   82.636364  4.070909  2.285727  19.137273   
6    19.742857  183.314286  122.285714  3.585714  3.117143  17.977143   
8    15.100000  353.100000  209.214286  3.229286  3.999214  16.772143   

           vs        am      gear      carb  
cyl                                          
4    0.909091  0.727273  4.090909  1.545455  
6    0.571429  0.428571  3.857143  3.428571  
8    0.000000  0.142857  3.285714  3.500000

In [5]:
# hp 변수에 대해서만 실린더 수 별로 평균값을 구한다면?
# 실린더 수 별로 마력의 평균
df.groupby(['cyl'])['hp'].mean()

cyl
4     82.636364
6    122.285714
8    209.214286
Name: hp, dtype: float64

In [6]:
# 특정 변수를 선택해 평균을 구하고 싶은 경우

print(df['hp'].mean())

#or
# 변수 선택
print(df.hp)

146.6875
0     110
1     110
2      93
3     110
4     175
5     105
6     245
7      62
8      95
9     123
10    123
11    180
12    180
13    180
14    205
15    215
16    230
17     66
18     52
19     65
20     97
21    150
22    150
23    245
24    175
25     66
26     91
27    113
28    264
29    175
30    335
31    109
Name: hp, dtype: int64


In [7]:
# 변수 안에서 슬라이싱
df.hp[30]

335

In [8]:
# 여러값 슬라이싱
df.hp[0:3]

0    110
1    110
2     93
Name: hp, dtype: int64

In [9]:
# 변수만 선택했을때 자료형 조사:type()
type(df.hp)

pandas.core.series.Series

In [3]:
# hp 변수만 따로 저장하는 series 만들기

s = df.hp
s

0     110
1     110
2      93
3     110
4     175
5     105
6     245
7      62
8      95
9     123
10    123
11    180
12    180
13    180
14    205
15    215
16    230
17     66
18     52
19     65
20     97
21    150
22    150
23    245
24    175
25     66
26     91
27    113
28    264
29    175
30    335
31    109
Name: hp, dtype: int64

In [5]:
# seriese 의 index부분을 models(차 이름)으로 설정한다
s.index = df.model
s

model
Mazda RX4              110
Mazda RX4 Wag          110
Datsun 710              93
Hornet 4 Drive         110
Hornet Sportabout      175
Valiant                105
Duster 360             245
Merc 240D               62
Merc 230                95
Merc 280               123
Merc 280C              123
Merc 450SE             180
Merc 450SL             180
Merc 450SLC            180
Cadillac Fleetwood     205
Lincoln Continental    215
Chrysler Imperial      230
Fiat 128                66
Honda Civic             52
Toyota Corolla          65
Toyota Corona           97
Dodge Challenger       150
AMC Javelin            150
Camaro Z28             245
Pontiac Firebird       175
Fiat X1-9               66
Porsche 914-2           91
Lotus Europa           113
Ford Pantera L         264
Ferrari Dino           175
Maserati Bora          335
Volvo 142E             109
Name: hp, dtype: int64

In [12]:
# series: 이름으로 선택하기
s['Datsun 710']

93

In [13]:
# :기호 사용
s['Datsun 710':'Valiant']

model
Datsun 710            93
Hornet 4 Drive       110
Hornet Sportabout    175
Valiant              105
Name: hp, dtype: int64

In [6]:
# series 연산도 가능하다
print(s*2)

model
Mazda RX4              220
Mazda RX4 Wag          220
Datsun 710             186
Hornet 4 Drive         220
Hornet Sportabout      350
Valiant                210
Duster 360             490
Merc 240D              124
Merc 230               190
Merc 280               246
Merc 280C              246
Merc 450SE             360
Merc 450SL             360
Merc 450SLC            360
Cadillac Fleetwood     410
Lincoln Continental    430
Chrysler Imperial      460
Fiat 128               132
Honda Civic            104
Toyota Corolla         130
Toyota Corona          194
Dodge Challenger       300
AMC Javelin            300
Camaro Z28             490
Pontiac Firebird       350
Fiat X1-9              132
Porsche 914-2          182
Lotus Europa           226
Ford Pantera L         528
Ferrari Dino           350
Maserati Bora          670
Volvo 142E             218
Name: hp, dtype: int64


In [7]:
# pandas의 series의 통계 값을 구하는 함수
print('평균')
print(df.hp.mean())
print('표준편차')
print(df.hp.std())
print('분산')
print(df.hp.var())

평균
146.6875
표준편차
68.56286848932059
분산
4700.866935483871


## numpy

In [8]:
import numpy as np

#numpy 기본 함수
print(np.mean(df.hp)) #평균
print(np.std(df.hp)) #표준편차
print(np.var(df.hp)) # 분산

146.6875
67.48307079371833
4553.96484375


In [9]:
# 일차원 벡터 만들기

a = np.array(list(range(8)))
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
# a를 이차원 apxmflrtmfh aksemfrl

a.reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
# reshape(): 행렬의 구조를 바꿀 수 있다.

a.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [12]:
# reshape()로 3차원 행렬 만들어보기
a.reshape((2,2,2))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
# zeros(): 모든 원소가 0으로 채워진 행렬 만들기

np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# full(,x): 0이 아닌 x라는 원소로 모든 원소값 초기화

np.full((2,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [15]:
# eye(): nXn 행렬의 대각선으로만 1인 행렬 만들기

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# 직접 한번에 만들기

a = np.array([[0,1,2], [3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

### 메트릭스 연산하기

In [19]:
# 1. 벡터(ndarray) 만들기

a = np.array(list(range(1, 10)))
print('a:', a)
b = np.array(list(range(11, 20)))
print('b:', b)

a: [1 2 3 4 5 6 7 8 9]
b: [11 12 13 14 15 16 17 18 19]


In [20]:
# 2. shape()를 재정의해서 Matrix를 만든다

a = a.reshape(3,3)
b = b.reshape(3,3)

print('a:', a)
print('b:', b)

a: [[1 2 3]
 [4 5 6]
 [7 8 9]]
b: [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [23]:
# 3. 두 매트릭스 연산하기

print('a+b:', a+b)
print('a-b:', a-b)
print('a*b:', a*b)
print('a/b:', a/b)

a+b: [[12 14 16]
 [18 20 22]
 [24 26 28]]
a-b: [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
a*b: [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
a/b: [[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]


In [24]:
# 행렬곱 적용하기:dot()
a.dot(b)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])